### ISSUE TITLE
Creating Schemas with nw.js causes errors. 

### ISSUE THREAD

**Issue by hamoy** [Ivshti/linvodb3#10]
This is the error I get when I open:
     LevelUPError: Could not locate LevelDOWN, try `npm install level down`

So I install Leveldown and this is the error I get:
     LevelUPError: Installed version of LevelDOWN (1.3.0) does not match required version (~0.10.0)

----------- ERROR without LevelDOWN installed

LevelUPError: Could not locate LevelDOWN, try `npm install leveldown`
    at getLevelDOWN (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.MDZ5rk/node_modules/linvodb3/node_modules/levelup/lib/util.js:55:11)
    at LevelUP.open (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.MDZ5rk/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:113:37)
    at new LevelUP (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.MDZ5rk/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:86:8)
    at LevelUP (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.MDZ5rk/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:46:12)
    at Function.Model.initStore (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.MDZ5rk/node_modules/linvodb3/lib/model.js:79:100)
    at new Model (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.MDZ5rk/node_modules/linvodb3/lib/model.js:52:35)
    at eval (file:///var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.MDZ5rk/main.js:16:14)

----------- ERROR with LevelDOWN installed

LevelUPError: Installed version of LevelDOWN (1.3.0) does not match required version (~0.10.0)
    at getLevelDOWN (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.G62FcM/node_modules/linvodb3/node_modules/levelup/lib/util.js:59:11)
    at LevelUP.open (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.G62FcM/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:113:37)
    at new LevelUP (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.G62FcM/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:86:8)
    at LevelUP (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.G62FcM/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:46:12)
    at Function.Model.initStore (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.G62FcM/node_modules/linvodb3/lib/model.js:79:100)
    at new Model (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.G62FcM/node_modules/linvodb3/lib/model.js:52:35)
    at eval (file:///var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.G62FcM/main.js:16:14)

----------- CODE I'M RUNNIG

var os = require('os');
var LinvoDB = require("linvodb3");
var modelName = "persons";
var schema = { }; // Non-strict always, can be left empty

options.filename = "/temp"; // Path to database - not necessary 
options.store = { db: require("medeadown") }; // Options passed to LevelUP constructor 

var Person = new LinvoDB("person", { 
    name: { type: String, default: "nameless" }, // default value
    age: Number, // shorthand to { type: ... }
    created: Date, 
    address: { // nested object
        line1: String,
        line2: String
    }
}, { });

**Comment by Ivshti** [comment]
Run
```
npm install leveldown@0.10.x
```

**Comment by hamoy** [comment]
I installed and it still the same error I even put a copy of the module folder inside the levelup module but still get the same error.

LevelUPError: Could not locate LevelDOWN, try `npm install leveldown`
    at getLevelDOWN (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.ZyCuaC/node_modules/linvodb3/node_modules/levelup/lib/util.js:71:11)
    at LevelUP.open (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.ZyCuaC/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:113:37)
    at new LevelUP (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.ZyCuaC/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:86:8)
    at LevelUP (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.ZyCuaC/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:46:12)
    at Function.Model.initStore (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.ZyCuaC/node_modules/linvodb3/lib/model.js:79:100)
    at new Model (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.ZyCuaC/node_modules/linvodb3/lib/model.js:52:35)
    at eval (file:///var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.ZyCuaC/main.js:16:14)

**Comment by Ivshti** [comment]
How about you set the back-end manually

```javascript
LinvoDB.defaults.store = { db: require("leveldown") };
```

**Comment by hamoy** [comment]
Now I get this:

Error: dlopen(/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.IGeSw1/node_modules/leveldown/build/Release/leveldown.node, 1): no suitable image found.  Did find:
/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.IGeSw1/node_modules/leveldown/build/Release/leveldown.node: mach-o, but wrong architecture
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:360:17)
    at require (module.js:376:17)
    at bindings (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.IGeSw1/node_modules/leveldown/node_modules/bindings/bindings.js:76:44)
    at Object.eval (/private/var/folders/ff/n5r157j92tdc6322388y_2th0000gn/T/.org.chromium.Chromium.IGeSw1/node_modules/leveldown/index.js:1:99)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:360:17)

In Windows I get this error in the console:

Uncaught Error: %1 is not a valid Win32 application.
C:\Users\LOCALU~1\AppData\Local\Temp\nw4332_31991\node_modules\leveldown\build\Release\leveldown.node

**Comment by Ivshti** [comment]
You have to re-compile leveldown for NW.js.
You have to use nw-gyp for this

Or, easier, use medeadown instead, which is JS only and similar in performance.
```javascript
LinvoDB.defaults.store = { db: require("medeadown") };
```
