### ISSUE TITLE
Failing to call via remote/Electron

### ISSUE THREAD

**Issue by rwilsonjr** [Ivshti/linvodb3#11]
Calling this from renderer code:

var db = window.remote.require('linvodb3');
var medea = window.remote.require("medeadown");
var path = window.remote.require('path');
var User = new db('users', {}, { filename: path.join(__dirname, "data") + 'users.db', store: { db: medea }});

Error thrown:
------------
Uncaught Error: db.open is not a function
TypeError: db.open is not a function
    at LevelUP.open (/Volumes/Seagate/development/techops-clock/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:116:6)
    at new LevelUP (/Volumes/Seagate/development/techops-clock/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:86:8)
    at LevelUP (/Volumes/Seagate/development/techops-clock/node_modules/linvodb3/node_modules/levelup/lib/levelup.js:46:12)
    at Function.Model.initStore (/Volumes/Seagate/development/techops-clock/node_modules/linvodb3/lib/model.js:79:100)
    at new Model (/Volumes/Seagate/development/techops-clock/node_modules/linvodb3/lib/model.js:52:35)
    at EventEmitter.<anonymous> (/Volumes/Seagate/development/techops-clock/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/lib/rpc-server.js:181:13)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/Volumes/Seagate/development/techops-clock/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:64:23)
    at emitTwo (events.js:87:13)

**Comment by Ivshti** [comment]
I doubt this can possibly work - unless the objects are really simple, they have to be adapted for the electron IPC.

Is it 100% required by your use case to include linvodb through remote - you don't have to - you can directly include it in your BrowserWindow.

If you **have** to include it through remote, e.g. one db for several browser processes, I would suggest initializing it in the main process and then exposing it by creating an additional script called "initdb", doing the init of all models there, and exposing them through module.exports.

Then, use remote.require("./initdb") in your BrowserWindow(s).

**Comment by Ivshti** [comment]
Closed since it's not intended to work through Electron IPC
