### ISSUE TITLE
When I run the update operation, the error occurred: Cannot redefine property

### ISSUE THREAD

**Issue by yunfong** [Ivshti/linvodb3#12]
This my schema 

    var User = new LinvoDB('user',{
	id:{type:Number,index:true,unique:true},
	user:{
		id:{type:Number,index:true,unique:true},
		username:{type:String,index:true,unique: true},
		userLabelName:String,
		portraitUrl:String,
		email:String,
		phoneNumber:String,
		birthday:String,
		firstName:String
	}
    },{});

    module.exports = User;

when I execute below code:

    UserDoc.update({id:userprofile.id},userprofile,{upsert:true},function(){});

-------------------

Uncaught Exception:
TypeError: Cannot redefine property: email
    at Function.defineProperty (native)
    at E:\electron\app\app\node_modules\linvodb3\lib\schemas.js:70:10
    at forOwn (E:\electron\app\app\node_modules\linvodb3\node_modules\lodash\dist\lodash.js:2106:15)
    at Function.forEach (E:\electron\app\app\node_modules\linvodb3\node_modules\lodash\dist\lodash.js:3303:9)
    at construct (E:\electron\app\app\node_modules\linvodb3\lib\schemas.js:58:4)
    at E:\electron\app\app\node_modules\linvodb3\lib\schemas.js:68:20
    at forOwn (E:\electron\app\app\node_modules\linvodb3\node_modules\lodash\dist\lodash.js:2106:15)
    at Function.forEach (E:\electron\app\app\node_modules\linvodb3\node_modules\lodash\dist\lodash.js:3303:9)
    at Object.construct (E:\electron\app\app\node_modules\linvodb3\lib\schemas.js:58:4)
    at Document (E:\electron\app\app\node_modules\linvodb3\lib\document.js:799:11)

**Comment by Ivshti** [comment]
We're probably looking at a bug here. Shouldn't be too hard to fix. What is userprofile? Is it a instance of the model or a plain object?

Also, a couple pieces of advice:
1. you have 3 id properties in this schema - the default _id (which you can re-use), id and user.id 
2. if userprofile is an instance of a model, you can just call userprofile.save() instead of that update operation
3. why are most properties nested under user? you can make this simpler and move those proerties to the top level, since it's a user model anyway

**Comment by Ivshti** [comment]
This might have been fixed in 3.9.1 - can you please test?

**Comment by Ivshti** [comment]
Closed because this is fixed.
