### ISSUE TITLE
Updating Levelup and Leveldown

### ISSUE THREAD

**Issue by detj** [Ivshti/linvodb3#13]
Any plans to upgrade both the dependencies? Will upgrading them break the existing sutff in any way?

**Comment by Ivshti** [comment]
There's a very easy way to try - update them and run npm test. Currently, 3 tests fail (not implemented functionalities) so if you get the same result then it's all good.

**Comment by detj** [comment]
I am getting this error when I run tests. I am just trying out tests, didn't upgrade any package at this point.

```
 Cursor
    Without sorting
      1) "before each" hook

  ✖ 1 of 293 tests failed:

  1) Cursor "before each" hook:
     OpenError: IO error: workspace/test.db/LOCK: No such file or directory
      at /Users/detj/src/linvodb3/node_modules/levelup/lib/levelup.js:118:34
```

How do I setup the test db?

**Comment by detj** [comment]
Solved by creating a directory called `workspace`

**Comment by detj** [comment]
Ran the tests, 6 of 293 tests failed

```
1) Database #getIdsForQuery Can use a compound index to get docs with a basic match:
     Error: not implemented - TODO
      at Context.<anonymous> (/Users/detj/src/linvodb3/test/db.test.js:523:19)
      at Test.Runnable.run (/Users/detj/src/linvodb3/node_modules/mocha/lib/runnable.js:187:15)
      at Runner.runTest (/Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:299:10)
      at /Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:345:12
      at next (/Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:227:14)
      at /Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:236:7
      at next (/Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:184:23)
      at /Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:204:5
      at process._tickCallback (node.js:448:13)

  2) Database #getIdsForQuery Can use an index to get sorted docs via compound sort:
     Error: not implemented - TODO
      at Context.<anonymous> (/Users/detj/src/linvodb3/test/db.test.js:868:19)
      at Test.Runnable.run (/Users/detj/src/linvodb3/node_modules/mocha/lib/runnable.js:187:15)
      at Runner.runTest (/Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:299:10)
      at /Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:345:12
      at next (/Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:227:14)
      at /Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:236:7
      at next (/Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:184:23)
      at /Users/detj/src/linvodb3/node_modules/mocha/lib/runner.js:204:5
      at process._tickCallback (node.js:448:13)

  3) Database Update If a multi update fails on one document, previous updates should be rolled back:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/Users/detj/src/linvodb3/node_modules/mocha/lib/runnable.js:158:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  4) Database Update If an index constraint is violated by an update, all changes should be rolled back:
     Error: timeout of 10000ms exceeded
      at null.<anonymous> (/Users/detj/src/linvodb3/node_modules/mocha/lib/runnable.js:158:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  5) Database Update Updates are atomic:
     expected null to equal undefined


  6) Database Using indexes Updating indexes upon document update Updating docs still works as before with indexing:
     expected null to equal undefined
```

**Comment by Ivshti** [comment]
Actually I forgot about the last 3 issues, they are created by another bug which is also documented in Issues

So it seems updating the deps brings no additional issues.

Perhaps only the workspace directory one - maybe we'll have to put a mkdir somewhere in the code.

**Comment by detj** [comment]
Yeah, agreed. I ran the tests before upgrading leveldown & levelup and then ran the tests again after upgrading leveldown@1.1.0 & levelup@1.2.1

The tests results are same for both the cases (6 out 293 tests fail). So, yeah I assume packages could be updated.

**Comment by detj** [comment]
Tried it with leveldown@1.3.0 too, tests are passing.

**Comment by detj** [comment]
Sending a PR
