### ISSUE TITLE
Close method

### ISSUE THREAD

**Issue by simon-p-r** [Ivshti/linvodb3#41]
Hi

Is there a close method to clean up on shutdown?

Thanks

**Comment by Ivshti** [comment]
what kind of close? delete the data? otherwise you should call the sync/close method of your back-end store; should probably make a wrapper around that

**Comment by simon-p-r** [comment]
Close to let you cleanly close down process.  How would you call close method on the back-end store?

**Comment by buehler** [comment]
I'd also like to know how to cleanly teardown the database. My usecase is to temporarily store data in linvodb. After some operations the db can be closed and the files deleted. So how can I ensure the "shutdown" of the database and then safely delete the db files?

**Comment by Ivshti** [comment]
The problem is that the closing method depends on the particular store and is not universal I think.

I have to research this 

What store do you use?

**Comment by depeele** [comment]
Is there any new information on how exactly you properly close?

My interest is the proper way to close a database cleanly, leaving data intact.

I need this for two scenarios:
- when the program exits;
- when the user wishes to open a different database;

I'm using a live cursor, and stopping the live cursor before closing the data store doesn't seem to be enough.

With code similar to the following:
``` javascript
const Linvodb = require('linvodb3');
const Medeadown = require('medeadown');

LinvoDb.dbPath = '/path/to/my/data/dir';
LinvoDb.defaults.store = { db: Medeadown };
...
const db = new LinvoDb( 'db-name', {}, {autoIndexing:true, autoLoad:true});
let live = null;

db.buildIndexes( () => {
  live = db.find( myQuery ).live();
});

...
live.stop();
db.store.close();
```

Following the `db.store.close()`, I get the following error:
```
ReadError: Database is not open
    at maybeError (C:\Users\dep\cygwin\home\dep\src\uc.electron.lit\app\node_modules\levelup\lib\levelup.js:293:32)
    at LevelUP.get (C:\Users\dep\cygwin\home\dep\src\uc.electron.lit\app\node_modules\levelup\lib\levelup.js:153:7)
    at Function.Cursor.retriever (C:\Users\dep\cygwin\home\dep\src\uc.electron.lit\app\node_modules\linvodb3\lib\cursor.js:355:17)
    at C:\Users\dep\cygwin\home\dep\src\uc.electron.lit\app\node_modules\linvodb3\lib\cursor.js:332:16
    at Timeout._onTimeout (C:\Users\dep\cygwin\home\dep\src\uc.electron.lit\app\node_modules\bagpipe\lib\bagpipe.js:157:34)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

**Comment by depeele** [comment]
The following code, placed at [line 349 of lib/cursor.js](https://github.com/Ivshti/linvodb3/blob/6952de376e4761167cb0f9c29342d16d675874bf/lib/cursor.js#L349) solves the error issues:
```
if (! task.db.store.isOpen()) return cb();
```
I'm not familiar enough with the code to know if this is the best solution...
