### ISSUE TITLE
Tests and Benchmarks don't work out-of-the-box

### ISSUE THREAD

**Issue by YurySolovyov** [Ivshti/linvodb3#62]
I was going to start poking with the module, but noticed that test that present on the repo do not run OOB, same if for benchmarks.
Tests error:
```
npm t

> linvodb3@3.25.0 test /home/yury-linux/dev/linvodb3
> mocha --reporter spec --timeout 10000

(node:7607) DeprecationWarning: child_process: options.customFds option is deprecated. Use options.stdio instead.


  Cursor
    Without sorting
      1) "before each" hook

  ✖ 1 of 294 tests failed:

  1) Cursor "before each" hook:
     OpenError: IO error: workspace/test.db/LOCK: No such file or directory
      at /home/yury-linux/dev/linvodb3/node_modules/levelup/lib/levelup.js:119:34
      at /home/yury-linux/dev/linvodb3/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16


npm ERR! Test failed.  See above for more details.
```
Benchmarks error:
```
node benchmarks/find.js 
module.js:471
    throw err;
    ^

Error: Cannot find module '../lib/customUtils'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/yury-linux/dev/linvodb3/benchmarks/commonUtilities.js:5:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by YurySolovyov** [comment]
`customUtils` were not called, so I applied:
```diff
diff --git a/benchmarks/commonUtilities.js b/benchmarks/commonUtilities.js
index 164ec7f..c161311 100644
--- a/benchmarks/commonUtilities.js
+++ b/benchmarks/commonUtilities.js
@@ -2,8 +2,7 @@
  * Functions that are used in several benchmark tests
  */
 
-var customUtils = require('../lib/customUtils')
-  , fs = require('fs')
+var fs = require('fs')
   , path = require('path')
   , Datastore = require('../lib/model')
   , executeAsap   // process.nextTick or setImmediate depending on your Node version
@@ -146,12 +145,12 @@ module.exports.findDocsWithIn = function (d, n, profiler, cb) {
   // Preparing all the $in arrays, will take some time
   for (i = 0; i < n; i += 1) {
     ins[i] = [];
-    
+
```

And the next thing as about locks again:
```
node benchmarks/find.js 
----------------------------
Test with 10000 documents
Don't use an index
Use a persistent datastore
----------------------------

events.js:160
      throw er; // Unhandled 'error' event
      ^
OpenError: IO error: workspace/find.bench.db/LOCK: No such file or directory
    at /home/yury-linux/dev/linvodb3/node_modules/levelup/lib/levelup.js:119:34
    at /home/yury-linux/dev/linvodb3/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
```

**Comment by YurySolovyov** [comment]
Hm, might be the mocha issue - bumping to 3.2.0 made a lots of tests pass, some still fail though
