### ISSUE TITLE
Continuously getting failures when npm installing this library

### ISSUE THREAD

**Issue by adragoset** [Ivshti/linvodb3#80]
node version v6.10.0

Fails while trying to pull the bagpipe dependency.

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install' ]
2 info using npm@5.0.3
3 info using node@v6.10.0
4 verbose npm-session 62fcc32dfea01cc9
5 silly install runPreinstallTopLevelLifecycles
6 silly preinstall data_visualizer@0.0.0
7 info lifecycle data_visualizer@0.0.0~preinstall: data_visualizer@0.0.0
8 silly lifecycle data_visualizer@0.0.0~preinstall: no script for preinstall, continuing
9 silly install loadCurrentTree
10 silly install readLocalPackageData
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 silly install loadShrinkwrap
14 silly install loadAllDepsIntoIdealTree
15 http fetch GET 304 https://registry.npmjs.org/linvodb3 683ms (from cache)
16 silly pacote range manifest for linvodb3@^3.25.0 fetched in 697ms
17 http fetch GET 304 https://registry.npmjs.org/leveldown 717ms (from cache)
18 silly pacote range manifest for leveldown@^1.7.2 fetched in 767ms
19 http fetch GET 304 https://registry.npmjs.org/async 127ms (from cache)
20 silly pacote range manifest for async@1.x.x fetched in 137ms
21 http fetch GET 304 https://registry.npmjs.org/hat 188ms (from cache)
22 silly pacote version manifest for hat@0.0.3 fetched in 192ms
23 http fetch GET 304 https://registry.npmjs.org/prebuild-install 112ms (from cache)
24 silly pacote range manifest for prebuild-install@^2.1.0 fetched in 114ms
25 http fetch GET 304 https://registry.npmjs.org/expand-template 139ms (from cache)
26 silly pacote range manifest for expand-template@^1.0.2 fetched in 142ms
27 http fetch GET 304 https://registry.npmjs.org/github-from-package 169ms (from cache)
28 silly pacote version manifest for github-from-package@0.0.0 fetched in 186ms
29 http fetch GET 304 https://registry.npmjs.org/nan 448ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/fast-future 450ms (from cache)
31 http fetch GET 304 https://registry.npmjs.org/abstract-leveldown 451ms (from cache)
32 silly pacote range manifest for nan@~2.6.1 fetched in 454ms
33 silly pacote range manifest for fast-future@~1.0.2 fetched in 455ms
34 silly pacote range manifest for abstract-leveldown@~2.6.1 fetched in 456ms
35 http fetch GET 304 https://registry.npmjs.org/binary-search-tree 491ms (from cache)
36 http fetch GET 304 https://registry.npmjs.org/levelup 494ms (from cache)
37 silly pacote version manifest for binary-search-tree@0.2.6 fetched in 497ms
38 http fetch GET 304 https://registry.npmjs.org/underscore 497ms (from cache)
39 silly pacote range manifest for levelup@^1.2.1 fetched in 498ms
40 silly pacote range manifest for underscore@1.8.x fetched in 503ms
41 http fetch GET 304 https://registry.npmjs.org/path 515ms (from cache)
42 silly pacote range manifest for path@^0.12.7 fetched in 516ms
43 http fetch GET 304 https://registry.npmjs.org/minimist 128ms (from cache)
44 silly pacote range manifest for minimist@^1.2.0 fetched in 130ms
45 http fetch GET 304 https://registry.npmjs.org/bindings 508ms (from cache)
46 silly pacote range manifest for bindings@~1.2.1 fetched in 510ms
47 http fetch GET 304 https://registry.npmjs.org/mkdirp 171ms (from cache)
48 silly pacote range manifest for mkdirp@^0.5.1 fetched in 174ms
49 http fetch GET 304 https://registry.npmjs.org/node-abi 134ms (from cache)
50 http fetch GET 304 https://registry.npmjs.org/npmlog 135ms (from cache)
51 http fetch GET 304 https://registry.npmjs.org/noop-logger 139ms (from cache)
52 silly pacote range manifest for node-abi@^2.0.0 fetched in 141ms
53 silly pacote range manifest for npmlog@^4.0.1 fetched in 140ms
54 http fetch GET 304 https://registry.npmjs.org/os-homedir 137ms (from cache)
55 silly pacote range manifest for noop-logger@^0.1.1 fetched in 149ms
56 silly pacote range manifest for underscore@~1.4.4 fetched in 10ms
57 silly pacote range manifest for os-homedir@^1.0.1 fetched in 144ms
58 http fetch GET 304 https://registry.npmjs.org/pump 161ms (from cache)
59 silly pacote range manifest for pump@^1.0.1 fetched in 165ms
60 http fetch GET 304 https://registry.npmjs.org/rc 162ms (from cache)
61 http fetch GET 304 https://registry.npmjs.org/tar-fs 139ms (from cache)
62 http fetch GET 304 https://registry.npmjs.org/simple-get 151ms (from cache)
63 silly pacote range manifest for rc@^1.1.6 fetched in 166ms
64 silly pacote range manifest for tar-fs@^1.13.0 fetched in 144ms
65 silly pacote range manifest for simple-get@^1.4.2 fetched in 158ms
66 http fetch GET 304 https://registry.npmjs.org/tunnel-agent 143ms (from cache)
67 silly pacote range manifest for tunnel-agent@^0.4.3 fetched in 145ms
68 http fetch GET 304 https://registry.npmjs.org/xtend 145ms (from cache)
69 http fetch GET 304 https://registry.npmjs.org/xtend 154ms (from cache)
70 silly pacote range manifest for xtend@~4.0.0 fetched in 149ms
71 silly pacote version manifest for xtend@4.0.1 fetched in 160ms
72 http fetch GET 304 https://registry.npmjs.org/level-codec 140ms (from cache)
73 http fetch GET 304 https://registry.npmjs.org/deferred-leveldown 142ms (from cache)
74 silly pacote version manifest for minimist@0.0.8 fetched in 5ms
75 http fetch GET 304 https://registry.npmjs.org/level-errors 141ms (from cache)
76 silly pacote range manifest for level-codec@~6.1.0 fetched in 145ms
77 silly pacote range manifest for deferred-leveldown@~1.2.1 fetched in 147ms
78 silly pacote range manifest for level-errors@~1.0.3 fetched in 148ms
79 http fetch GET 304 https://registry.npmjs.org/level-iterator-stream 141ms (from cache)
80 silly pacote range manifest for level-iterator-stream@~1.3.0 fetched in 142ms
81 http fetch GET 304 https://registry.npmjs.org/semver 145ms (from cache)
82 silly pacote range manifest for semver@~5.1.0 fetched in 149ms
83 http fetch GET 304 https://registry.npmjs.org/process 169ms (from cache)
84 http fetch GET 304 https://registry.npmjs.org/prr 173ms (from cache)
85 silly pacote range manifest for process@^0.11.1 fetched in 172ms
86 silly pacote range manifest for prr@~1.0.1 fetched in 175ms
87 http fetch GET 304 https://registry.npmjs.org/util 166ms (from cache)
88 silly pacote range manifest for util@^0.10.3 fetched in 167ms
89 http fetch GET 304 https://registry.npmjs.org/are-we-there-yet 110ms (from cache)
90 silly pacote range manifest for are-we-there-yet@~1.1.2 fetched in 111ms
91 silly pacote range manifest for pump@^1.0.0 fetched in 1ms
92 http fetch GET 304 https://registry.npmjs.org/gauge 124ms (from cache)
93 silly pacote range manifest for gauge@~2.7.3 fetched in 126ms
94 http fetch GET 304 https://registry.npmjs.org/end-of-stream 124ms (from cache)
95 http fetch GET 304 https://registry.npmjs.org/set-blocking 128ms (from cache)
96 silly pacote range manifest for end-of-stream@^1.1.0 fetched in 132ms
97 silly pacote range manifest for set-blocking@~2.0.0 fetched in 137ms
98 silly pacote range manifest for abstract-leveldown@~2.4.0 fetched in 10ms
99 silly pacote range manifest for xtend@^4.0.0 fetched in 11ms
100 http fetch GET 304 https://registry.npmjs.org/console-control-strings 162ms (from cache)
101 silly pacote range manifest for console-control-strings@~1.1.0 fetched in 163ms
102 silly pacote range manifest for level-errors@^1.0.3 fetched in 1ms
103 http fetch GET 304 https://registry.npmjs.org/once 146ms (from cache)
104 http fetch GET 304 https://registry.npmjs.org/deep-extend 131ms (from cache)
105 silly pacote range manifest for deep-extend@~0.4.0 fetched in 135ms
106 silly pacote range manifest for once@^1.3.1 fetched in 151ms
107 http fetch GET 304 https://registry.npmjs.org/ini 133ms (from cache)
108 http fetch GET 304 https://registry.npmjs.org/strip-json-comments 134ms (from cache)
109 silly pacote range manifest for ini@~1.3.0 fetched in 135ms
110 silly pacote range manifest for strip-json-comments@~2.0.1 fetched in 135ms
111 http fetch GET 304 https://registry.npmjs.org/chownr 134ms (from cache)
112 silly pacote range manifest for chownr@^1.0.1 fetched in 135ms
113 silly pacote range manifest for console-control-strings@^1.0.0 fetched in 1ms
114 http fetch GET 304 https://registry.npmjs.org/tar-stream 112ms (from cache)
115 silly pacote range manifest for tar-stream@^1.1.2 fetched in 116ms
116 http fetch GET 304 https://registry.npmjs.org/unzip-response 113ms (from cache)
117 silly pacote range manifest for unzip-response@^1.0.0 fetched in 117ms
118 http fetch GET 304 https://registry.npmjs.org/errno 111ms (from cache)
119 silly pacote range manifest for errno@~0.1.1 fetched in 113ms
120 http fetch GET 304 https://registry.npmjs.org/inherits 114ms (from cache)
121 silly pacote range manifest for inherits@^2.0.1 fetched in 117ms
122 http fetch GET 304 https://registry.npmjs.org/inherits 105ms (from cache)
123 silly pacote version manifest for inherits@2.0.1 fetched in 107ms
124 http fetch GET 304 https://registry.npmjs.org/readable-stream 126ms (from cache)
125 silly pacote range manifest for readable-stream@^1.0.33 fetched in 133ms
126 silly pacote range manifest for once@^1.4.0 fetched in 3ms
127 http fetch GET 304 https://registry.npmjs.org/delegates 132ms (from cache)
128 silly pacote range manifest for delegates@^1.0.0 fetched in 133ms
129 http fetch GET 304 https://registry.npmjs.org/readable-stream 129ms (from cache)
130 silly pacote range manifest for readable-stream@^2.0.6 fetched in 133ms
131 silly pacote range manifest for end-of-stream@^1.0.0 fetched in 3ms
132 http fetch GET 304 https://registry.npmjs.org/aproba 137ms (from cache)
133 silly pacote range manifest for readable-stream@^2.0.0 fetched in 5ms
134 silly pacote range manifest for aproba@^1.0.3 fetched in 142ms
135 http fetch GET 304 https://registry.npmjs.org/has-unicode 136ms (from cache)
136 silly pacote range manifest for prr@~0.0.0 fetched in 4ms
137 silly pacote range manifest for has-unicode@^2.0.0 fetched in 140ms
138 http fetch GET 304 https://registry.npmjs.org/object-assign 131ms (from cache)
139 silly pacote range manifest for object-assign@^4.1.0 fetched in 132ms
140 silly pacote range manifest for inherits@~2.0.1 fetched in 1ms
141 silly pacote range manifest for inherits@~2.0.3 fetched in 1ms
142 http fetch GET 304 https://registry.npmjs.org/signal-exit 121ms (from cache)
143 silly pacote range manifest for signal-exit@^3.0.0 fetched in 132ms
144 http fetch GET 304 https://registry.npmjs.org/string-width 120ms (from cache)
145 silly pacote range manifest for string-width@^1.0.1 fetched in 122ms
146 http fetch GET 304 https://registry.npmjs.org/strip-ansi 119ms (from cache)
147 silly pacote range manifest for strip-ansi@^3.0.1 fetched in 122ms
148 http fetch GET 304 https://registry.npmjs.org/wide-align 111ms (from cache)
149 silly pacote range manifest for wide-align@^1.1.0 fetched in 113ms
150 http fetch GET 304 https://registry.npmjs.org/wrappy 127ms (from cache)
151 silly pacote range manifest for wrappy@1 fetched in 129ms
152 http fetch GET 304 https://registry.npmjs.org/bl 124ms (from cache)
153 silly pacote range manifest for bl@^1.0.0 fetched in 126ms
154 http fetch GET 304 https://registry.npmjs.org/isarray 116ms (from cache)
155 silly pacote range manifest for isarray@~1.0.0 fetched in 117ms
156 silly pacote range manifest for strip-ansi@^3.0.0 fetched in 3ms
157 http fetch GET 304 https://registry.npmjs.org/isarray 139ms (from cache)
158 http fetch GET 304 https://registry.npmjs.org/core-util-is 141ms (from cache)
159 silly pacote version manifest for isarray@0.0.1 fetched in 141ms
160 silly pacote range manifest for core-util-is@~1.0.0 fetched in 143ms
161 silly pacote range manifest for string-width@^1.0.2 fetched in 3ms
162 silly pacote range manifest for readable-stream@^2.0.5 fetched in 3ms
163 http fetch GET 304 https://registry.npmjs.org/string_decoder 143ms (from cache)
164 silly pacote range manifest for string_decoder@~0.10.x fetched in 146ms
165 http fetch GET 304 https://registry.npmjs.org/process-nextick-args 119ms (from cache)
166 silly pacote range manifest for process-nextick-args@~1.0.6 fetched in 120ms
167 http fetch GET 304 https://registry.npmjs.org/string_decoder 110ms (from cache)
168 http fetch GET 304 https://registry.npmjs.org/safe-buffer 115ms (from cache)
169 silly pacote range manifest for string_decoder@~1.0.0 fetched in 111ms
170 silly pacote range manifest for safe-buffer@~5.1.0 fetched in 116ms
171 http fetch GET 304 https://registry.npmjs.org/util-deprecate 111ms (from cache)
172 silly pacote range manifest for util-deprecate@~1.0.1 fetched in 112ms
173 http fetch GET 304 https://registry.npmjs.org/code-point-at 137ms (from cache)
174 silly pacote range manifest for code-point-at@^1.0.0 fetched in 139ms
175 http fetch GET 304 https://registry.npmjs.org/is-fullwidth-code-point 134ms (from cache)
176 silly pacote range manifest for is-fullwidth-code-point@^1.0.0 fetched in 135ms
177 http fetch GET 304 https://registry.npmjs.org/ansi-regex 108ms (from cache)
178 silly pacote range manifest for ansi-regex@^2.0.0 fetched in 110ms
179 http fetch GET 304 https://registry.npmjs.org/number-is-nan 140ms (from cache)
180 silly pacote range manifest for number-is-nan@^1.0.0 fetched in 143ms
181 silly pacote range manifest for leveldown@^1.7.2 fetched in 2ms
182 silly resolveWithNewModule leveldown@1.7.2 checking installable status
183 silly pacote range manifest for linvodb3@^3.25.0 fetched in 7ms
184 silly resolveWithNewModule linvodb3@3.25.0 checking installable status
185 silly pacote range manifest for fast-future@~1.0.2 fetched in 6ms
186 silly resolveWithNewModule fast-future@1.0.2 checking installable status
187 silly pacote range manifest for nan@~2.6.1 fetched in 8ms
188 silly resolveWithNewModule nan@2.6.2 checking installable status
189 silly pacote range manifest for abstract-leveldown@~2.6.1 fetched in 9ms
190 silly resolveWithNewModule abstract-leveldown@2.6.1 checking installable status
191 silly pacote range manifest for prebuild-install@^2.1.0 fetched in 10ms
192 silly resolveWithNewModule prebuild-install@2.1.2 checking installable status
193 silly pacote range manifest for bindings@~1.2.1 fetched in 11ms
194 silly resolveWithNewModule bindings@1.2.1 checking installable status
195 silly pacote range manifest for xtend@~4.0.0 fetched in 2ms
196 silly resolveWithNewModule xtend@4.0.1 checking installable status
197 silly pacote range manifest for expand-template@^1.0.2 fetched in 7ms
198 silly resolveWithNewModule expand-template@1.0.3 checking installable status
199 silly pacote range manifest for minimist@^1.2.0 fetched in 9ms
200 silly resolveWithNewModule minimist@1.2.0 checking installable status
201 silly pacote range manifest for noop-logger@^0.1.1 fetched in 10ms
202 silly resolveWithNewModule noop-logger@0.1.1 checking installable status
203 silly pacote range manifest for mkdirp@^0.5.1 fetched in 10ms
204 silly resolveWithNewModule mkdirp@0.5.1 checking installable status
205 silly pacote range manifest for npmlog@^4.0.1 fetched in 10ms
206 silly resolveWithNewModule npmlog@4.1.2 checking installable status
207 silly pacote range manifest for node-abi@^2.0.0 fetched in 11ms
208 silly resolveWithNewModule node-abi@2.0.3 checking installable status
209 silly pacote version manifest for github-from-package@0.0.0 fetched in 11ms
210 silly resolveWithNewModule github-from-package@0.0.0 checking installable status
211 silly pacote range manifest for os-homedir@^1.0.1 fetched in 12ms
212 silly resolveWithNewModule os-homedir@1.0.2 checking installable status
213 silly pacote range manifest for pump@^1.0.1 fetched in 12ms
214 silly resolveWithNewModule pump@1.0.2 checking installable status
215 silly pacote range manifest for rc@^1.1.6 fetched in 8ms
216 silly resolveWithNewModule rc@1.2.1 checking installable status
217 silly pacote range manifest for simple-get@^1.4.2 fetched in 6ms
218 silly resolveWithNewModule simple-get@1.4.3 checking installable status
219 silly pacote range manifest for tar-fs@^1.13.0 fetched in 3ms
220 silly resolveWithNewModule tar-fs@1.15.3 checking installable status
221 silly pacote range manifest for tunnel-agent@^0.4.3 fetched in 2ms
222 silly resolveWithNewModule tunnel-agent@0.4.3 checking installable status
223 silly pacote version manifest for minimist@0.0.8 fetched in 0ms
224 silly resolveWithNewModule minimist@0.0.8 checking installable status
225 silly pacote range manifest for are-we-there-yet@~1.1.2 fetched in 2ms
226 silly resolveWithNewModule are-we-there-yet@1.1.4 checking installable status
227 silly pacote range manifest for gauge@~2.7.3 fetched in 3ms
228 silly resolveWithNewModule gauge@2.7.4 checking installable status
229 silly pacote range manifest for console-control-strings@~1.1.0 fetched in 3ms
230 silly resolveWithNewModule console-control-strings@1.1.0 checking installable status
231 silly pacote range manifest for set-blocking@~2.0.0 fetched in 4ms
232 silly resolveWithNewModule set-blocking@2.0.0 checking installable status
233 silly pacote range manifest for delegates@^1.0.0 fetched in 1ms
234 silly resolveWithNewModule delegates@1.0.0 checking installable status
235 silly pacote range manifest for readable-stream@^2.0.6 fetched in 2ms
236 silly resolveWithNewModule readable-stream@2.3.2 checking installable status
237 silly pacote range manifest for core-util-is@~1.0.0 fetched in 5ms
238 silly resolveWithNewModule core-util-is@1.0.2 checking installable status
239 silly pacote range manifest for string_decoder@~1.0.0 fetched in 5ms
240 silly resolveWithNewModule string_decoder@1.0.3 checking installable status
241 silly pacote range manifest for isarray@~1.0.0 fetched in 5ms
242 silly resolveWithNewModule isarray@1.0.0 checking installable status
243 silly pacote range manifest for process-nextick-args@~1.0.6 fetched in 6ms
244 silly resolveWithNewModule process-nextick-args@1.0.7 checking installable status
245 silly pacote range manifest for safe-buffer@~5.1.0 fetched in 6ms
246 silly resolveWithNewModule safe-buffer@5.1.1 checking installable status
247 silly pacote range manifest for util-deprecate@~1.0.1 fetched in 6ms
248 silly resolveWithNewModule util-deprecate@1.0.2 checking installable status
249 silly pacote range manifest for inherits@~2.0.3 fetched in 7ms
250 silly resolveWithNewModule inherits@2.0.3 checking installable status
251 silly pacote range manifest for string-width@^1.0.1 fetched in 7ms
252 silly resolveWithNewModule string-width@1.0.2 checking installable status
253 silly pacote range manifest for aproba@^1.0.3 fetched in 7ms
254 silly resolveWithNewModule aproba@1.1.2 checking installable status
255 silly pacote range manifest for has-unicode@^2.0.0 fetched in 8ms
256 silly resolveWithNewModule has-unicode@2.0.1 checking installable status
257 silly pacote range manifest for object-assign@^4.1.0 fetched in 10ms
258 silly resolveWithNewModule object-assign@4.1.1 checking installable status
259 silly pacote range manifest for signal-exit@^3.0.0 fetched in 11ms
260 silly resolveWithNewModule signal-exit@3.0.2 checking installable status
261 silly pacote range manifest for wide-align@^1.1.0 fetched in 9ms
262 silly resolveWithNewModule wide-align@1.1.2 checking installable status
263 silly pacote range manifest for strip-ansi@^3.0.1 fetched in 13ms
264 silly resolveWithNewModule strip-ansi@3.0.1 checking installable status
265 silly pacote range manifest for is-fullwidth-code-point@^1.0.0 fetched in 1ms
266 silly resolveWithNewModule is-fullwidth-code-point@1.0.0 checking installable status
267 silly pacote range manifest for code-point-at@^1.0.0 fetched in 1ms
268 silly resolveWithNewModule code-point-at@1.1.0 checking installable status
269 silly pacote range manifest for number-is-nan@^1.0.0 fetched in 1ms
270 silly resolveWithNewModule number-is-nan@1.0.1 checking installable status
271 silly pacote range manifest for ansi-regex@^2.0.0 fetched in 1ms
272 silly resolveWithNewModule ansi-regex@2.1.1 checking installable status
273 silly pacote range manifest for end-of-stream@^1.1.0 fetched in 1ms
274 silly resolveWithNewModule end-of-stream@1.4.0 checking installable status
275 silly pacote range manifest for once@^1.3.1 fetched in 1ms
276 silly resolveWithNewModule once@1.4.0 checking installable status
277 silly pacote range manifest for wrappy@1 fetched in 0ms
278 silly resolveWithNewModule wrappy@1.0.2 checking installable status
279 silly pacote range manifest for deep-extend@~0.4.0 fetched in 2ms
280 silly resolveWithNewModule deep-extend@0.4.2 checking installable status
281 silly pacote range manifest for ini@~1.3.0 fetched in 3ms
282 silly resolveWithNewModule ini@1.3.4 checking installable status
283 silly pacote range manifest for strip-json-comments@~2.0.1 fetched in 3ms
284 silly resolveWithNewModule strip-json-comments@2.0.1 checking installable status
285 silly pacote range manifest for unzip-response@^1.0.0 fetched in 2ms
286 silly resolveWithNewModule unzip-response@1.0.2 checking installable status
287 silly pacote range manifest for chownr@^1.0.1 fetched in 3ms
288 silly resolveWithNewModule chownr@1.0.1 checking installable status
289 silly pacote range manifest for tar-stream@^1.1.2 fetched in 3ms
290 silly resolveWithNewModule tar-stream@1.5.4 checking installable status
291 silly pacote range manifest for bl@^1.0.0 fetched in 1ms
292 silly resolveWithNewModule bl@1.2.1 checking installable status
293 silly pacote range manifest for async@1.x.x fetched in 35ms
294 silly resolveWithNewModule async@1.5.2 checking installable status
295 silly pacote version manifest for binary-search-tree@0.2.6 fetched in 23ms
296 silly resolveWithNewModule binary-search-tree@0.2.6 checking installable status
297 silly pacote range manifest for levelup@^1.2.1 fetched in 24ms
298 silly resolveWithNewModule levelup@1.3.8 checking installable status
299 silly pacote range manifest for underscore@1.8.x fetched in 25ms
300 silly resolveWithNewModule underscore@1.8.3 checking installable status
301 silly pacote version manifest for hat@0.0.3 fetched in 25ms
302 silly resolveWithNewModule hat@0.0.3 checking installable status
303 silly pacote range manifest for path@^0.12.7 fetched in 25ms
304 silly resolveWithNewModule path@0.12.7 checking installable status
305 silly pacote git manifest for util@github:ivshti/node-util fetched in 3134ms
306 silly resolveWithNewModule util@0.10.3 checking installable status
307 silly pacote git manifest for bagpipe@github:ivshti/bagpipe fetched in 3150ms
308 silly resolveWithNewModule bagpipe@0.3.7 checking installable status
309 silly fetchPackageMetaData error for inherits@git://github.com/ivshti/inherits.git exited with error code: 128
310 verbose stack Error: exited with error code: 128
310 verbose stack     at ChildProcess.onexit (C:\Program Files\nodejs\node_modules\npm\node_modules\mississippi\node_modules\end-of-stream\index.js:39:36)
310 verbose stack     at emitTwo (events.js:106:13)
310 verbose stack     at ChildProcess.emit (events.js:191:7)
310 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
311 verbose cwd C:\Users\adragose\Documents\Source\data_visualizer\app
312 verbose Windows_NT 6.1.7601
313 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
314 verbose node v6.10.0
315 verbose npm  v5.0.3
316 error exited with error code: 128
317 verbose exit [ 1, true ]
```

**Comment by adragoset** [comment]
CLosing, fixed by https://github.com/Ivshti/bagpipe/pull/1
