### ISSUE TITLE
Integration problems in enectron

### ISSUE THREAD

**Issue by fullee** [Ivshti/linvodb3#99]
## Operating environment

![image](https://user-images.githubusercontent.com/11188837/44385510-3337db00-a552-11e8-932a-d492acbf8f61.png)

## The following is devtools error message

```
Uncaught 
err
cause
:
undefined
message
:
"Failed to require LevelDOWN (A dynamic link library (DLL) initialization routine failed.
↵\\?\C:\Users\full\Desktop\electron-start\electron-quick-start\node_modules\leveldown\build\Release\leveldown.node). Try `npm install leveldown` if it's missing"
name
:
"LevelUPError"
stack
:
"LevelUPError: Failed to require LevelDOWN (A dynamic link library (DLL) initialization routine failed.
↵\\?\C:\Users\full\Desktop\electron-start\electron-quick-start\node_modules\leveldown\build\Release\leveldown.node). Try `npm install leveldown` if it's missing↵    at requireError (C:\Users\full\Desktop\electron-start\electron-quick-start\node_modules\levelup\lib\leveldown.js:37:10)↵    at getLevelDOWN (C:\Users\full\Desktop\electron-start\electron-quick-start\node_modules\levelup\lib\leveldown.js:31:11)↵    at LevelUP.open (C:\Users\full\Desktop\electron-start\electron-quick-start\node_modules\levelup\lib\levelup.js:112:34)↵    at new LevelUP (C:\Users\full\Desktop\electron-start\electron-quick-start\node_modules\levelup\lib\levelup.js:84:8)↵    at LevelUP (C:\Users\full\Desktop\electron-start\electron-quick-start\node_modules\levelup\lib\levelup.js:45:44)↵    at Function.Model.initStore (C:\Users\full\Desktop\electron-start\electron-quick-start\node_modules\linvodb3\lib\model.js:79:100)↵    at new Model (C:\Users\full\Desktop\electron-start\electron-quick-start\node_modules\linvodb3\lib\model.js:52:35)↵    at Object.<anonymous> (C:\Users\full\Desktop\electron-start\electron-quick-start\renderer.js:2:10)↵    at Object.<anonymous> (C:\Users\full\Desktop\electron-start\electron-quick-start\renderer.js:23:3)↵    at Module._compile (module.js:642:30)"
type
:
"LevelUPError"
__proto__
:
Error
```

**Comment by fullee** [comment]
Just now, it was solved by changing to medeadown.

**Comment by jnosornov** [comment]
@Ivshti I guess, this one can be closed!
